# Generated by Django 4.0 on 2021-12-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_event_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description2',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.event')),
            ],
            options={
                'ordering': ('event',),
            },
        ),
    ]
