# Generated by Django 4.0 on 2021-12-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_event_description2_eventlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
