# Generated by Django 4.0 on 2021-12-28 18:12

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_event_list1_event_list2_event_list3_delete_eventlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(upload_to=base_app.models.Gallery.get_file_name)),
            ],
        ),
    ]
