# Generated by Django 4.0 on 2021-12-28 19:10

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=base_app.models.Chief.get_file_name)),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
            options={
                'ordering': ('post',),
            },
        ),
    ]
