# Generated by Django 4.0 on 2021-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField(max_length=300)),
                ('upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-upload',),
            },
        ),
    ]
