# Generated by Django 4.0 on 2021-12-28 19:52

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default=1, upload_to=base_app.models.Reviews.get_file_name),
            preserve_default=False,
        ),
    ]
