# Generated by Django 4.0 on 2021-12-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-upload',)},
        ),
    ]
