# Generated by Django 4.0 on 2021-12-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
